table Sales_State
	lineageTag: 13e1320e-9cec-459e-9c98-95f7ad121c88

	column StateID
		dataType: int64
		formatString: 0
		lineageTag: 373dc59c-dfee-43a3-9b89-b277ab93e5ad
		summarizeBy: none
		sourceColumn: StateID

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 8fa7e210-1fbe-4462-a5e3-8de42409697b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Capital
		dataType: string
		lineageTag: 88c4cda3-b957-48e9-adb5-b07b4246ddaa
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Capital

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 61624cdb-bd4a-4bce-829c-d114c16f295f
		dataCategory: County
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	partition Sales_State = m
		mode: import
		queryGroup: 'Data Model'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\paddy\Documents\Analytics_files\Powerbi\Ruth Power BI\Sales_Data1.xlsx"), null, true),
				    Table_6_Table = Source{[Item="Table_6",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table_6_Table,{{"StateID", Int64.Type}, {"State", type text}, {"Capital", type text}, {"Zone", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

