table Sales_Channel
	lineageTag: 3fa34397-a2b3-4cf5-93d9-5a2c10333a76

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 78c8fa54-a884-49be-8724-362f6f05d5a9
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: 1bf70b61-0e43-47bd-93f9-475e18dc09a1
		summarizeBy: none
		sourceColumn: ChannelName

		annotation SummarizationSetBy = Automatic

	partition Sales_Channel = m
		mode: import
		queryGroup: 'Data Model'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\paddy\Documents\Analytics_files\Powerbi\Ruth Power BI\Sales_Data1.xlsx"), null, true),
				    Table_1_Table = Source{[Item="Table_1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table_1_Table,{{"ChannelKey", Int64.Type}, {"ChannelName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

